# These are supported funding model platforms
github: mkwilbux
patreon: WickedSmart
open_collective: copper-linux-user-group
buy_me_a_coffee: faqlinux
custom: venmo - @Marcia-Wilbur
paypal: admin@raspbian.io  
